planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    use_sim_time: true

    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerLattice"
      tolerance: 0.5
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      terminal_checking_interval: 5000
      max_planning_time: 3.5
      motion_model_for_search: "DUBIN"
      cost_travel_multiplier: 2.0
      angle_quantization_bins: 64
      analytic_expansion_ratio: 3.5
      analytic_expansion_max_length: 3.0
      analytic_expansion_max_cost: 200.0
      analytic_expansion_max_cost_override: false
      minimum_turning_radius: 0.40
      reverse_penalty: 2.1
      change_penalty: 0.0
      non_straight_penalty: 1.0
      cost_penalty: 2.5
      retrospective_penalty: 0.025
      # lattice_filepath: "" # The filepath to the state lattice graph
      rotation_penalty: 5.0
      lookup_table_size: 20.0
      cache_obstacle_heuristic: true
      allow_reverse_expansion: false
      smooth_path: true
      debug_visualizations: true
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
