name: ROS Code Formatter
on:
  push:
    branches: [ feature/checktty]  # Adjust branch names as needed
    # Or use: branches: [ '**' ]  # to run on all branches

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AutoModality/action-ros-clang-format@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
